# Generated by Django 2.1.4 on 2018-12-08 16:53

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(upload_to='')),
                ('author', models.CharField(max_length=256)),
                ('content', models.TextField()),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('film_name', models.CharField(max_length=256)),
                ('title', models.CharField(max_length=256)),
                ('film_url', models.CharField(max_length=256)),
                ('trailer_url', models.CharField(max_length=256)),
                ('top', models.BigIntegerField()),
                ('photo', models.ImageField(upload_to='')),
                ('description', tinymce.models.HTMLField(verbose_name='Description')),
                ('content', tinymce.models.HTMLField(verbose_name='Content')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256)),
                ('photo', models.ImageField(upload_to='')),
                ('content', tinymce.models.HTMLField(verbose_name='Content')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Movies.Film'),
        ),
    ]
