# Generated by Django 2.1.4 on 2018-12-15 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0007_auto_20181214_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='header_photo',
            field=models.ImageField(default=1, upload_to='film_images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='film',
            name='year',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
