# Generated by Django 2.1.4 on 2018-12-15 10:26

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0008_auto_20181215_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='content_en',
            field=tinymce.models.HTMLField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='film',
            name='content_uk',
            field=tinymce.models.HTMLField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='film',
            name='description_en',
            field=tinymce.models.HTMLField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='film',
            name='description_uk',
            field=tinymce.models.HTMLField(null=True, verbose_name='Description'),
        ),
        migrations.AddField(
            model_name='film',
            name='film_name_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='film_name_uk',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='film',
            name='photo_en',
            field=models.ImageField(null=True, upload_to='film_images'),
        ),
        migrations.AddField(
            model_name='film',
            name='photo_uk',
            field=models.ImageField(null=True, upload_to='film_images'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_en',
            field=tinymce.models.HTMLField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='news',
            name='content_uk',
            field=tinymce.models.HTMLField(null=True, verbose_name='Content'),
        ),
        migrations.AddField(
            model_name='news',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='news',
            name='title_uk',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
