# Generated by Django 2.1.4 on 2018-12-15 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Movies', '0010_auto_20181215_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='film',
            name='film_photo_en',
        ),
        migrations.RemoveField(
            model_name='film',
            name='film_photo_uk',
        ),
    ]
